промежуток
htmlacademy-react/980203-six-cities-9 pull request #5
Opened 2022-03-06 17:00 UTC by saveliybyru

2022-03-06 17:04 UTC, knenkne requested changes

2022-03-06 17:04 UTC, knenkne commented on project/src/components/main-screen/main-screen.tsx
> +                {offers.map((offer)=>{<PlaceCard offer={offer}></PlaceCard>;})}
Ошибка тут. Ты из `map` ничего не возвращаешь, убирай фигурные скобки или пиши с `return`

2022-03-07 18:39 UTC, knenkne commented on project/src/components/error-screen/error-screen.tsx
> +        <Link className="footer__logo-link" to="main.html">
В `to` надо класть один из роутов, которые ты записал в `<App />`

2022-03-07 18:39 UTC, knenkne commented on project/src/components/header/header.tsx
> +                <Link className="header__nav-link header__nav-link--profile" to="/">
А почему бы не использовать `AppRoute`?

2022-03-07 18:39 UTC, knenkne commented on project/src/components/place-card/place-card.tsx
> +          <Link to={`offer/${id}`}>
Используй `AppRoute` во всех ссылках

2022-03-08 02:01 UTC, saveliybyru commented on project/src/components/place-card/place-card.tsx
> +          <Link to={`offer/${id}`}>
не понял о чём именно тут речь.
В задании указано следующее: Используя компонент Link и хуки из пакета react-router-dom свяжите страницы приложения. Например, клик по заголовку карточки предложения должен переводить пользователя на страницу «Room» с подробным описанием предложения по аренде.

Я Линком и связал страницы. Почему это неправильно и как связать другими способами?

2022-03-08 11:22 UTC, merged